server:
  port: 8081

spring:
  application:
    name: form-workflow-engine

  # PostgreSQL Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/form_workflow_db
    username: postgres
    password: Raji@585
    driver-class-name: org.postgresql.Driver


  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # Keycloak OAuth2 Configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/form-workflow-engine
          #jwk-set-uri: http://localhost:8180/realms/form-workflow-engine/protocol/openid-connect/certs

# Logging
logging:
  level:
    com.example.form_workflow_engine: DEBUG
    org.springframework.security: DEBUG
